services:
  - type: web
    name: session-messenger-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm run backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MASTER_KEY
        generateValue: true
